version: "2"

services:
  redis:
    image: daocloud.io/daocloud/dao-redis:master-init
    environment:
    - REDIS_PASS=**None**

  worker:
    image: daocloud.io/airywenter/sync-dockerhub
    environment:
    - TARGET_REGISTRY_API=http://localhost:5000/v2
    - TARGET_REGISTRY=localhost:5000
    - REDIS_URL=redis://localhost:6379/0
    - PROD=1

    volumes:
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock



